from deepeval.metrics import GEval
from deepeval.models import OllamaModel
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval import evaluate
import json

local_judge = OllamaModel(model="llama3.2")


paraphrase_metric = GEval(
    name="Paraphrase quality",
    criteria="Determine whether the actual_output accurately converts "
        "the core meaning and intent of the input. The task is to produce a given incident into a rephrased version which does not have any company information or proprietary information and should focus only on the AI tasks of the original use-case prior to this incident occuring.\n It should not describe the incident itself on rephrasing.",
    evaluation_params=[SingleTurnParams.INPUT, SingleTurnParams.ACTUAL_OUTPUT],
    evaluation_steps=[
        "Compare the Input with the Actual Output. Analyze if the ai task in the Input is converted to a generic use-case in the same space in Actual Output. It should not have any specifics of the input. ",
        "If there is no proprietary information in Actual Output as compared to Input, it is good.",
        "Use the following FEW-SHOT EXAMPLES to anchor your scoring alignment:",
        
        # Low Score Example
        "[EXAMPLE 1 - LOW SCORE]"
        "Actual Output: 'An automated license‑plate reader misread a “7” as a “2,” mistakenly alerting local police to a supposedly stolen Oldsmobile. The officer was unable to confirm this before pulling over a BMW in a Kansas City suburb'"
        "Input: 'An automated license plate reader (ALPR) camera misread a 7 as a 2 and incorrectly alerted the local police about a stolen Oldsmobile car, which was allegedly not able to be verified by an officer before a traffic stop was effected on a BMW in Kansas City suburb.'"
        "Score: 0.3"
        "Reasoning: Actual Output just rephrases the Input and has specifics of the incident from the Input like license‑plate reader misread a “7” as a “2,”, stolen Oldsmobile, etc",

        # Low Score Example
        "[EXAMPLE 1 - LOW SCORE]"
        "Actual Output: 'A system is designed to analyze and group images of faces, aiming to provide a organized and searchable photo library for users. It utilizes facial recognition technology to identify and categorize faces, enabling users to easily find and manage their photos. The system's primary objective is to improve the user experience by automatically tagging and grouping similar faces.'"
        "Input: 'Amazon tweaked product-search algorithm to boost and guide customers towards more profitable in-house products instead of showing mainly most-relevant and best-selling listings, which its internal engineers and lawyers alleged to violate company\u2019s best-for-customer principle.'"
        "Score: 0.1"
        "Reasoning: Actual Output is abstract but the AI task and domain is not the same as the input",


        # Low Score Example
        "[EXAMPLE 2 - LOW SCORE]"
        "Actual Output: 'A system utilizing artificial intelligence is designed to analyze biometric data and recognize individual faces, providing insights for identity verification purposes. It aims to process and evaluate data from various sources, enabling the detection and identification of specific characteristics. The system seeks to enhance monitoring capabilities by leveraging advanced algorithms and machine learning techniques. It can monittor muslims in China'"
        "Input: 'A suite of AI-powered digital surveillance systems involving facial recognition and analysis of biometric data were deployed by the Chinese government in Xinjiang to monitor and discriminate local Uyghur and other Turkic Muslims.'"
        "Score: 0.3"
        "Reasoning: Actual Output correctly abstracts the Input into a generic use-case in the same space. It contains very few specific details from the input though like monittor muslims in China.",
        
        # High Score Example
        "[EXAMPLE 3 - HIGH SCORE]"
        "Actual Output: 'A system utilizing complex algorithms is designed to estimate property values by analyzing various factors and providing a predicted value. The goal of this system is to offer accurate and reliable assessments, which can be used to inform decision-making. This approach aims to leverage advanced technology to streamline the valuation process and improve overall efficiency.'"
        "Input: 'A home value generated by a black-box algorithm was reportedly defended by the Castricum court, which was criticized by a legal specialist for setting a dangerous precedent for accepting black-box algorithms as long as their results appear reasonable.'"
        "Score: 1.0"
        "Reasoning: Actual Output correctly abstracts the Input into a generic use-case in the same space. It does not have specific details from the input which is very good.",
        "Compare the target text against these examples to assign a final score from 0.0 to 1.0. Remember to check Input against Actual Output. Input will have proprietary information, not actual output. Make sure to clearly see what is Actual Output and what is the Input when scoring. Don't confuse input with Actual output."
    ],
    model=local_judge,
    threshold=0.7
)




with open("./rephrased_incidents.json") as f:
    use_cases = json.load(f)

with open("./aiid_incidents.json") as f:
    actual_use_cases = json.load(f)

use_cases  = use_cases[0:50]
actual_use_cases = actual_use_cases[0:50]
dataset = []
for i in range(len(use_cases)):
    testcase = LLMTestCase(
    input=actual_use_cases[i],
    actual_output=use_cases[i]
    )
    dataset.append(testcase)

output = evaluate(test_cases=dataset, metrics=[paraphrase_metric])

print(output)
